### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lgcambero** [graniet/LynxFramework#1]
Hello, I'm trying to test the tool, but I have the following error, I will describe a little: rhost genre in kali with http://localhost:8888, copies the server folder to Windows 10 and installed in chrome extension. You can give me some idea to solve the problem? You could describe a little using the tool? Thanks for your time.
![error](https://cloud.githubusercontent.com/assets/11602705/14195601/7d3833c4-f791-11e5-8f66-d048a8d9eb15.jpg)

**Comment by graniet** [comment]
Hello,

1) This based on "Mouseover" event please just enter email & password value & move mouse on button.
2) Check JS terminal for get login.

[image 1](http://s22.postimg.org/c7d8ih4og/Capture_d_e_cran_2016_04_01_a_09_43_34.jpg)


You can update script for get on RHOST but you need (HTTPS).

[image 2](http://s22.postimg.org/655lrzg8h/Capture_d_e_cran_2016_04_01_a_09_49_01.png)

#### Please (re)download with python script framework.

**Comment by lgcambero** [comment]
Thx. Solved.
